title: Mingnuo Teng's Homepage
page-top-title: Mingnuo Teng
top-section-bg-text: Limits define the notes, modes create the music
home-subtitle: Mingnuo Teng&ensp;|&ensp;滕明诺
copyright-text: '&copy; Mingnuo Teng 2026. All Rights Reserved.'
